In [1]:
import numpy as np
my_list = [1,2,3,4]
a=np.array(my_list)

In [3]:
a


array([1, 2, 3, 4])

In [4]:
one_vector = np.ones(4)

In [5]:
one_vector

array([ 1.,  1.,  1.,  1.])

In [8]:
one2darray = np.ones((2,4))

In [9]:
one2darray

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [11]:
my_list2=[2,3,4,5]
ar=np.array((my_list , my_list2))

In [12]:
ar

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [13]:
zero_vector = np.zeros(5)

In [16]:
ar[1,2]

4

In [17]:
my_matrix = np.array([[1, 2, 3], [4, 5, 6]])
print my_matrix

[[1 2 3]
 [4 5 6]]


In [18]:
print my_matrix[0:2,2]

[3 6]


In [19]:
print my_matrix[0,0:3]

[1 2 3]


In [20]:
fib_indices = np.array([1, 1, 2, 3])
random_vector = np.random.random(10)
print random_vector

[ 0.86983947  0.47975443  0.30084073  0.40294879  0.78778517  0.68216085
  0.50276623  0.59870277  0.40122024  0.84333539]


In [21]:
print random_vector[fib_indices]

[ 0.47975443  0.47975443  0.30084073  0.40294879]


In [23]:
my_vector = np.array([1,2,3,4])
select_index = np.array([True, False, True])
print my_vector[select_index]

[1 3]


C:\Users\sripr\Anaconda2\envs\gl-env\lib\site-packages\ipykernel\__main__.py:3: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 4 but corresponding boolean dimension is 3
  app.launch_new_instance()


In [24]:
my_array = np.array([1.0 , 2.0 , 3.0 , 4.0])
print my_array * my_array

[  1.   4.   9.  16.]


In [25]:
print my_array - np.ones(4)

[ 0.  1.  2.  3.]


In [26]:
print my_array + np.ones(4)

[ 2.  3.  4.  5.]


In [28]:
print my_array.np.mean()

AttributeError: 'numpy.ndarray' object has no attribute 'np'

In [29]:
print np.mean(my_array)

2.5


In [30]:
matrix_1 = np.array([[1., 2., 3.],[4., 5., 6.]])
matrix_2 = np.array([[1., 2.], [3., 4.], [5., 6.]])
print np.dot(matrix_1, matrix_2)

[[ 22.  28.]
 [ 49.  64.]]
